### ISSUE TITLE
Not working with scikit_learn:0.24 

### ISSUE THREAD

**Issue by gavishpoddar** [imadelh/NLP-news-classification#1]
Hi @imadel,
Thanks for the repo

ISSUE 

scikit_learn:0.24

ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'

Note: It's working with scikit_learn:0.22.2.post1 but with FutureWarning

`The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API`

**Comment by imadelh** [comment]
The requirements file has scikit-learn==0.21.3
